FROM nontakenusername/erlang-elixir-node:0.1.0-d9f40f3

USER root

RUN yum install -y epel-release \
    && yum update -y \
    && yum --enablerepo=epel -y install inotify-tools

ARG HOST_UID=${HOST_UID}
ARG HOST_GUID=${HOST_GUID}

# Change UID and GUID for the appuser to the host's user
RUN usermod -u ${HOST_UID} appuser \
    && groupmod -g ${HOST_GUID} appuser

USER appuser

CMD ["iex"]