pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'make build'
                sh 'make test'
            }
        }

        post { 
            always { 
                sh 'make cleanup'
            }
        }
    }
}