pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'make build'
                sh 'make unit_test'
            }
        }
    }
    
    post { 
        always { 
            sh 'make cleanup'
        }
    }
}